workflows:
  ios-unsigned:
    name: Quick iOS IPA Build
    max_build_duration: 30
    environment:
      flutter: "3.16.9"  # Fixed version for stability
      xcode: latest
    instance_type: mac_mini_m1  # Faster builds
    scripts:
      - name: QUICK FIX & BUILD
        script: |
          echo "âš¡ ULTRA-FAST BUILD STARTING..."
          
          # IMMEDIATE FIX: Update the broken dependency
          echo "ðŸ”§ FIXING code_text_field..."
          cp pubspec.yaml pubspec.yaml.backup
          
          # Method 1: Use Python (most reliable)
          python3 -c "
          import re
          with open('pubspec.yaml', 'r') as f:
              content = f.read()
          # Fix code_text_field from 2.3.0 to 1.1.0
          content = re.sub(r'code_text_field:\s*\^?2\.3\.0', 'code_text_field: ^1.1.0', content)
          with open('pubspec.yaml', 'w') as f:
              f.write(content)
          " || 
          
          # Method 2: If Python fails, use sed
          sed -i.bak 's/code_text_field.*2\.3\.0/code_text_field: ^1.1.0/g' pubspec.yaml
          
          echo "âœ… DEPENDENCY FIXED"
          
          # SKIP flutter clean to save time
          echo "ðŸ“¦ GETTING PACKAGES..."
          flutter pub get --verbose 2>&1 | tail -20
          
          # FORCE BUILD even if there are warnings
          echo "ðŸ—ï¸ BUILDING iOS APP..."
          flutter build ios --release --no-codesign --no-tree-shake-icons 2>&1 | tee build.log
          
          # Check if .app exists, build IPA anyway
          echo "ðŸ“¦ PACKAGING IPA..."
          if [ -d "build/ios/iphoneos/Runner.app" ]; then
            cd build/ios/iphoneos
            rm -rf Payload *.ipa 2>/dev/null || true
            mkdir Payload
            cp -r Runner.app Payload/
            zip -qr "app_unsigned.ipa" Payload
            echo "âœ… IPA CREATED: app_unsigned.ipa"
            ls -lh *.ipa
          else
            # Try alternative path
            if [ -d "build/ios/Release-iphoneos/Runner.app" ]; then
              cd build/ios/Release-iphoneos
              rm -rf Payload *.ipa 2>/dev/null || true
              mkdir Payload
              cp -r Runner.app Payload/
              zip -qr "app_unsigned.ipa" Payload
              echo "âœ… IPA CREATED from Release-iphoneos"
            else
              echo "âš ï¸ .app not found, checking build directory..."
              find build -name "*.app" -type d
              exit 1
            fi
          fi
          
          echo "ðŸŽ‰ BUILD SUCCESSFUL!"
          
      - name: EMERGENCY FALLBACK
        script: |
          # If main script failed, try emergency build
          echo "ðŸ†˜ TRYING EMERGENCY BUILD..."
          
          # Create minimal working pubspec
          cp pubspec.yaml.backup pubspec.yaml.original
          
          # Create emergency pubspec
          cat > pubspec_emergency.yaml << 'EOF'
          name: oled_editor
          description: Emergency build
          version: 1.0.0+1
          environment:
            sdk: ">=2.18.0 <4.0.0"
          dependencies:
            flutter:
              sdk: flutter
            code_text_field: ^1.1.0
          dev_dependencies:
            flutter_test:
              sdk: flutter
          flutter:
            uses-material-design: true
          EOF
          
          # Try emergency build
          cp pubspec_emergency.yaml pubspec.yaml
          flutter pub get
          flutter build ios --release --no-codesign
          
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload
          zip -qr emergency.ipa Payload
          echo "ðŸ†˜ EMERGENCY IPA CREATED"
    
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/Release-iphoneos/*.ipa
      - *.ipa
    
    # No caching to avoid conflicts
    cache:
      cache_paths: []
    
    # Auto-retry on failure
    automatic_retry_on_failure: true
    
    publishing:
      scripts:
        - name: Quick Success Message
          script: echo "âœ… IPA ready for download in artifacts!"