workflows:
  ios-build:
    name: Build OLED iOS
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: 🧹 Clean & Init
        script: |
          set -e # STOP immediately if this step fails
          rm -rf ios
          rm -f pubspec.lock
          flutter pub get
          
      - name: 🛠️ Generate iOS Project
        script: |
          set -e # STOP if generation fails
          flutter config --enable-ios
          flutter create . --platforms=ios
          
      - name: 🎨 Apply OLED Settings
        script: |
          set -e
          PLIST="ios/Runner/Info.plist"
          plutil -replace NSAppTransportSecurity -xml "<dict><key>NSAllowsArbitraryLoads</key><true/></dict>" $PLIST
          plutil -replace UIStatusBarHidden -bool YES $PLIST
          plutil -replace UIViewControllerBasedStatusBarAppearance -bool NO $PLIST
          plutil -replace UIFileSharingEnabled -bool YES $PLIST
          plutil -replace LSSupportsOpeningDocumentsInPlace -bool YES $PLIST

      - name: 📦 Install Pods
        script: |
          set -e
          cd ios
          # Fix for some plugins needing higher deployment target
          sed -i '' "s/# platform :ios, '12.0'/platform :ios, '13.0'/g" Podfile
          pod install
          cd ..

      - name: 🚀 Build IPA
        script: |
          set -e # STOP if build fails
          # Build unsigned release
          flutter build ios --release --no-codesign
          
          # Packaging
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r OLED_Editor.ipa Payload

    artifacts:
      - "*.ipa" 