workflows:
  ios-build:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Fix dependency and build
        script: |
          # Fix the version in pubspec.yaml
          sed -i '' 's/code_text_field:.*2\.3\.0/code_text_field: ^1.1.0/g' pubspec.yaml
          
          # Get packages
          flutter pub get
          
          # Build
          flutter build ios --release --no-codesign
          
          # Create IPA
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload
          zip -r app.ipa Payload
    artifacts:
      - build/ios/iphoneos/app.ipa