workflows:
  ios-build:
    name: Build OLED iOS
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: 🧹 Clean Windows Corruption
        script: |
          # Delete the corrupted Windows-generated folder
          rm -rf ios
          
          # Regenerate fresh iOS files on the Mac
          flutter config --enable-ios
          flutter create . --platforms=ios
          
      - name: 🎨 Apply OLED Settings
        script: |
          PLIST="ios/Runner/Info.plist"
          # Allow HTML & Hide Status Bar
          plutil -replace NSAppTransportSecurity -xml "<dict><key>NSAllowsArbitraryLoads</key><true/></dict>" $PLIST
          plutil -replace UIStatusBarHidden -bool YES $PLIST
          plutil -replace UIViewControllerBasedStatusBarAppearance -bool NO $PLIST
          plutil -replace UIFileSharingEnabled -bool YES $PLIST
          plutil -replace LSSupportsOpeningDocumentsInPlace -bool YES $PLIST

      - name: 📦 Install Pods
        script: |
          # Install dependencies manually
          cd ios
          pod install
          cd ..

      - name: 🚀 Build IPA
        script: |
          # Build the app (Unsigned)
          flutter build ios --release --no-codesign
          
          # Package the result
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r OLED_Editor.ipa Payload

    artifacts:
      - "*.ipa"