workflows:
  ios-unsigned:
    name: Unsigned iOS Build (AltStore)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Install CocoaPods
        script: |
          find . -name "Podfile" -exec dir dirname {} \; | xargs -n1 -I % sh -c 'cd %; pod install'

      - name: Build Flutter App (No Signing)
        script: |
          # Build the .app bundle without asking for code signing identities
          flutter build ios --release --no-codesign

      - name: Package .app into .ipa
        script: |
          # Go to the build output directory
          cd build/ios/iphoneos
          
          # Create the required "Payload" folder structure for an IPA
          mkdir Payload
          mv Runner.app Payload
          
          # Zip it up into an IPA file
          zip -r -9 runner.ipa Payload

    artifacts:
      - build/ios/iphoneos/*.ipa  # Save the file we just zipped
      - flutter_drive.log