workflows:
  ios-build:
    name: Build IPA
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build
        script: |
          # Fix dependency
          sed -i.bak 's/code_text_field: ^2.3.0/code_text_field: ^1.1.0/g' pubspec.yaml
          
          # Get packages
          flutter pub get
          
          # Fix deployment target
          cd ios
          cat > Podfile << 'EOF'
platform :ios, '13.0'
use_frameworks!
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
EOF
          
          pod install
          cd ..
          
          # Build
          flutter build ios --release --no-codesign
          
          # Create IPA
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r OLED_Editor.ipa Payload
          
    artifacts:
      - "build/ios/iphoneos/OLED_Editor.ipa"