workflows:
  ios-build:
    name: Build OLED iOS
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      # ADD THIS SINGLE FIX AT THE BEGINNING
      - name: Fix code_text_field
        script: |
          echo "Fixing broken dependency..."
          sed -i '' 's/code_text_field: ^2.3.0/code_text_field: ^1.1.0/g' pubspec.yaml
          
      # KEEP EVERYTHING ELSE EXACTLY AS YOUR OLD WORKING CODE
      - name: Generate Project
        script: |
          flutter config --enable-ios
          flutter create . --platforms=ios
      - name: Configure OLED Settings
        script: |
          PLIST="ios/Runner/Info.plist"
          plutil -replace NSAppTransportSecurity -xml "<dict><key>NSAllowsArbitraryLoads</key><true/></dict>" $PLIST
          plutil -replace UIStatusBarHidden -bool YES $PLIST
          plutil -replace UIViewControllerBasedStatusBarAppearance -bool NO $PLIST
          plutil -replace UIFileSharingEnabled -bool YES $PLIST
          plutil -replace LSSupportsOpeningDocumentsInPlace -bool YES $PLIST
      - name: Install Pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r OLED_Editor.ipa Payload
    artifacts:
      - "OLED_Editor.ipa"