workflows:
  ios-build:
    name: Build IPA
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          # Fix the dependency
          sed -i.bak 's/code_text_field: ^2.3.0/code_text_field: ^1.1.0/g' pubspec.yaml
          
          # Get packages
          flutter pub get
          
          # Install pods with fixed deployment target
          cd ios
          
          # Update Podfile first line to fix deployment target
          if grep -q "^platform :ios" Podfile; then
            sed -i.bak 's/^platform :ios.*/platform :ios, "13.0"/' Podfile
          else
            sed -i.bak '1s/^/platform :ios, "13.0"\
/' Podfile
          fi
          
          # Install pods
          pod install
          cd ..
          
          # Build the app
          flutter build ios --release --no-codesign
          
          # Create IPA
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload
          
          echo "✅ IPA created successfully"
          
    artifacts:
      - "build/ios/iphoneos/app.ipa"